# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social_graph.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'social_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12social_graph.proto\"N\n\x0bTransaction\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05node1\x18\x02 \x01(\x05\x12\r\n\x05node2\x18\x03 \x01(\x05\x12\x0e\n\x06weight\x18\x04 \x01(\x05\"(\n\x04Vote\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x06NodeId\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x04\x45\x64ge\x12\r\n\x05node1\x18\x01 \x01(\x05\x12\r\n\x05node2\x18\x02 \x01(\x05\x12\x0e\n\x06weight\x18\x03 \x01(\x05\" \n\x08\x45\x64geList\x12\x14\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x05.Edge\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"7\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xf9\x01\n\x0bSocialGraph\x12\x1e\n\x07Prepare\x12\x0c.Transaction\x1a\x05.Vote\x12\x1c\n\x06\x43ommit\x12\x0c.Transaction\x1a\x04.Ack\x12\x1e\n\x08GetEdges\x12\x07.NodeId\x1a\t.EdgeList\x12 \n\nInsertData\x12\x0c.Transaction\x1a\x04.Ack\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=22
  _globals['_TRANSACTION']._serialized_end=100
  _globals['_VOTE']._serialized_start=102
  _globals['_VOTE']._serialized_end=142
  _globals['_ACK']._serialized_start=144
  _globals['_ACK']._serialized_end=183
  _globals['_NODEID']._serialized_start=185
  _globals['_NODEID']._serialized_end=205
  _globals['_EDGE']._serialized_start=207
  _globals['_EDGE']._serialized_end=259
  _globals['_EDGELIST']._serialized_start=261
  _globals['_EDGELIST']._serialized_end=293
  _globals['_VOTEREQUEST']._serialized_start=295
  _globals['_VOTEREQUEST']._serialized_end=344
  _globals['_VOTERESPONSE']._serialized_start=346
  _globals['_VOTERESPONSE']._serialized_end=396
  _globals['_APPENDENTRIESREQUEST']._serialized_start=398
  _globals['_APPENDENTRIESREQUEST']._serialized_end=453
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=455
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=509
  _globals['_SOCIALGRAPH']._serialized_start=512
  _globals['_SOCIALGRAPH']._serialized_end=761
# @@protoc_insertion_point(module_scope)
