# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import social_graph_pb2 as social__graph__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in social_graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SocialGraphStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/SocialGraph/Prepare',
                request_serializer=social__graph__pb2.Transaction.SerializeToString,
                response_deserializer=social__graph__pb2.Vote.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/SocialGraph/Commit',
                request_serializer=social__graph__pb2.Transaction.SerializeToString,
                response_deserializer=social__graph__pb2.Ack.FromString,
                _registered_method=True)
        self.GetEdges = channel.unary_unary(
                '/SocialGraph/GetEdges',
                request_serializer=social__graph__pb2.NodeId.SerializeToString,
                response_deserializer=social__graph__pb2.EdgeList.FromString,
                _registered_method=True)
        self.InsertData = channel.unary_unary(
                '/SocialGraph/InsertData',
                request_serializer=social__graph__pb2.Transaction.SerializeToString,
                response_deserializer=social__graph__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/SocialGraph/RequestVote',
                request_serializer=social__graph__pb2.VoteRequest.SerializeToString,
                response_deserializer=social__graph__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/SocialGraph/AppendEntries',
                request_serializer=social__graph__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=social__graph__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)


class SocialGraphServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialGraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=social__graph__pb2.Transaction.FromString,
                    response_serializer=social__graph__pb2.Vote.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=social__graph__pb2.Transaction.FromString,
                    response_serializer=social__graph__pb2.Ack.SerializeToString,
            ),
            'GetEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdges,
                    request_deserializer=social__graph__pb2.NodeId.FromString,
                    response_serializer=social__graph__pb2.EdgeList.SerializeToString,
            ),
            'InsertData': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertData,
                    request_deserializer=social__graph__pb2.Transaction.FromString,
                    response_serializer=social__graph__pb2.Ack.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=social__graph__pb2.VoteRequest.FromString,
                    response_serializer=social__graph__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=social__graph__pb2.AppendEntriesRequest.FromString,
                    response_serializer=social__graph__pb2.AppendEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SocialGraph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SocialGraph', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SocialGraph(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/Prepare',
            social__graph__pb2.Transaction.SerializeToString,
            social__graph__pb2.Vote.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/Commit',
            social__graph__pb2.Transaction.SerializeToString,
            social__graph__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/GetEdges',
            social__graph__pb2.NodeId.SerializeToString,
            social__graph__pb2.EdgeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/InsertData',
            social__graph__pb2.Transaction.SerializeToString,
            social__graph__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/RequestVote',
            social__graph__pb2.VoteRequest.SerializeToString,
            social__graph__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SocialGraph/AppendEntries',
            social__graph__pb2.AppendEntriesRequest.SerializeToString,
            social__graph__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
